### ISSUE TITLE
Cross compiling fails to compile

### ISSUE THREAD

**Issue by 3m0W33D** [OpenByteDev/netcorehost#7]
Hi I am trying to cross compile a .dll on linux for windows using x86_64-pc-windows-gnu as, my target, however, the build keeps failing. Is this library not compatible for cross compiling yet?

**Comment by OpenByteDev** [comment]
How are you trying to compile and what is the result?

**Comment by 3m0W33D** [comment]
I am compiling from linux to windows using the nightly x86_64-pc-windows-gnu. My code is as follows, but I have removed some of the path information.

```rust
use std::path::Path;
use netcorehost::{pdcstring,nethost};
use std::error::Error;
use path_absolutize::Absolutize;

fn main() ->  Result<(), Box <dyn Error>> {
    use pdcstring::PdCString;
    
    let test_out_dir = Path::new("C:\\some\\pathonwindows\\").absolutize()?;
    let f_path = Path::join(&test_out_dir, "test.dll");
    let assembly_path = PdCString::from_os_str(f_path)?;
    let hostfxr = nethost::load_hostfxr()?;
    let context = hostfxr.initialize_for_dotnet_command_line(assembly_path)?;
    let result = context.run_app();
    
    Ok(())
}
```

The error I am getting is when compiling with `cargo build --target x86_64-pc-windows-gnu`
```bash
 $PATH/netcorehost-0.3.0/src/nethost.rs:40: undefined reference to `get_hostfxr_path'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)  
```

**Comment by OpenByteDev** [comment]
I just pushed some changes can you try it again with the current version on master?

**Comment by 3m0W33D** [comment]
Hi I am still pretty new to rust and I dont know if I am doing this right, but this is my cargo.toml
```
[package]
name = "dotnettest"
version = "0.1.0"
edition = "2018"

[dependencies]
netcorehost = { git = "https://github.com/OpenByteDev/netcorehost"}
path-absolutize = "3.0"
```
I tried compiling with `cargo build --target x86_64-pc-windows-gnu`  but I am still getting the same errors as above. Code has not change at all.

**Comment by OpenByteDev** [comment]
Can you run `cargo clean` and try again?

**Comment by 3m0W33D** [comment]
I have tried again with `cargo clean` and then building it, but the result is the same

**Comment by OpenByteDev** [comment]
Can you take a look into `target/debug/nethost` and tell me what files are inside?

**Comment by OpenByteDev** [comment]
Could you share a repo where the error occurs?

**Comment by OpenByteDev** [comment]
> 
> 
> I have tried and changed to use the latest cargo version 0.3.1 and there is a different error now.
> 
> ```shell
>   = note: /usr/bin/x86_64-w64-mingw32-ld:$PATH/target/x86_64-pc-windows-gnu/debug/nethost/win-x64/libnethost.lib: error adding symbols: file format not recognized
>           collect2: error: ld returned 1 exit status
> 
> 
> error: aborting due to previous error; 1 warning emitted
> 
> error: could not compile `dotnettest`
> ```

You should make a new comment instead of replacing an old one.

**Comment by OpenByteDev** [comment]
I'm not sure what's the problem. I assume the `libnethost.lib` ist incompatible with the `gnu` toolchain on windows.

Alternatively you could try to target `x86_64-pc-windows-msvc` using [cross](https://github.com/rust-embedded/cross).

**Comment by 3m0W33D** [comment]
The files inside there ar archive
```bash
ijwhost.lib:    current ar archive
libnethost.lib: current ar archive
nethost.lib:    current ar archive
```

**Comment by ArunGust** [comment]
Not sure exact issue, but working for me in ubuntu 20.4 LTS.

cstr = "0.2.8"
netcorehost = "^0.3.1"
path-absolutize = "3.0.10"
wchar = "0.10.1"

**Comment by OpenByteDev** [comment]
Are you sure you are building for windows? e.g. with `cargo build --target x86_64-pc-windows-gnu`?

**Comment by ArunGust** [comment]
Sorry, I am using  x86_64-unknown-linux-gnu
